# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ldennis/projects/projects-xcode/llcsv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ldennis/projects/projects-xcode/llcsv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ldennis/projects/projects-xcode/llcsv/CMakeFiles /Users/ldennis/projects/projects-xcode/llcsv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ldennis/projects/projects-xcode/llcsv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llcsv

# Build rule for target.
llcsv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 llcsv
.PHONY : llcsv

# fast build rule for target.
llcsv/fast:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/build
.PHONY : llcsv/fast

llcsv/csvcmds/csvappendcolumns.o: llcsv/csvcmds/csvappendcolumns.cpp.o

.PHONY : llcsv/csvcmds/csvappendcolumns.o

# target to build an object file
llcsv/csvcmds/csvappendcolumns.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvappendcolumns.cpp.o
.PHONY : llcsv/csvcmds/csvappendcolumns.cpp.o

llcsv/csvcmds/csvappendcolumns.i: llcsv/csvcmds/csvappendcolumns.cpp.i

.PHONY : llcsv/csvcmds/csvappendcolumns.i

# target to preprocess a source file
llcsv/csvcmds/csvappendcolumns.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvappendcolumns.cpp.i
.PHONY : llcsv/csvcmds/csvappendcolumns.cpp.i

llcsv/csvcmds/csvappendcolumns.s: llcsv/csvcmds/csvappendcolumns.cpp.s

.PHONY : llcsv/csvcmds/csvappendcolumns.s

# target to generate assembly for a file
llcsv/csvcmds/csvappendcolumns.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvappendcolumns.cpp.s
.PHONY : llcsv/csvcmds/csvappendcolumns.cpp.s

llcsv/csvcmds/csvappendrows.o: llcsv/csvcmds/csvappendrows.cpp.o

.PHONY : llcsv/csvcmds/csvappendrows.o

# target to build an object file
llcsv/csvcmds/csvappendrows.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvappendrows.cpp.o
.PHONY : llcsv/csvcmds/csvappendrows.cpp.o

llcsv/csvcmds/csvappendrows.i: llcsv/csvcmds/csvappendrows.cpp.i

.PHONY : llcsv/csvcmds/csvappendrows.i

# target to preprocess a source file
llcsv/csvcmds/csvappendrows.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvappendrows.cpp.i
.PHONY : llcsv/csvcmds/csvappendrows.cpp.i

llcsv/csvcmds/csvappendrows.s: llcsv/csvcmds/csvappendrows.cpp.s

.PHONY : llcsv/csvcmds/csvappendrows.s

# target to generate assembly for a file
llcsv/csvcmds/csvappendrows.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvappendrows.cpp.s
.PHONY : llcsv/csvcmds/csvappendrows.cpp.s

llcsv/csvcmds/csvcmds.o: llcsv/csvcmds/csvcmds.cpp.o

.PHONY : llcsv/csvcmds/csvcmds.o

# target to build an object file
llcsv/csvcmds/csvcmds.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvcmds.cpp.o
.PHONY : llcsv/csvcmds/csvcmds.cpp.o

llcsv/csvcmds/csvcmds.i: llcsv/csvcmds/csvcmds.cpp.i

.PHONY : llcsv/csvcmds/csvcmds.i

# target to preprocess a source file
llcsv/csvcmds/csvcmds.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvcmds.cpp.i
.PHONY : llcsv/csvcmds/csvcmds.cpp.i

llcsv/csvcmds/csvcmds.s: llcsv/csvcmds/csvcmds.cpp.s

.PHONY : llcsv/csvcmds/csvcmds.s

# target to generate assembly for a file
llcsv/csvcmds/csvcmds.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvcmds.cpp.s
.PHONY : llcsv/csvcmds/csvcmds.cpp.s

llcsv/csvcmds/csvinputfiles.o: llcsv/csvcmds/csvinputfiles.cpp.o

.PHONY : llcsv/csvcmds/csvinputfiles.o

# target to build an object file
llcsv/csvcmds/csvinputfiles.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvinputfiles.cpp.o
.PHONY : llcsv/csvcmds/csvinputfiles.cpp.o

llcsv/csvcmds/csvinputfiles.i: llcsv/csvcmds/csvinputfiles.cpp.i

.PHONY : llcsv/csvcmds/csvinputfiles.i

# target to preprocess a source file
llcsv/csvcmds/csvinputfiles.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvinputfiles.cpp.i
.PHONY : llcsv/csvcmds/csvinputfiles.cpp.i

llcsv/csvcmds/csvinputfiles.s: llcsv/csvcmds/csvinputfiles.cpp.s

.PHONY : llcsv/csvcmds/csvinputfiles.s

# target to generate assembly for a file
llcsv/csvcmds/csvinputfiles.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvinputfiles.cpp.s
.PHONY : llcsv/csvcmds/csvinputfiles.cpp.s

llcsv/csvcmds/csvjoincolumns.o: llcsv/csvcmds/csvjoincolumns.cpp.o

.PHONY : llcsv/csvcmds/csvjoincolumns.o

# target to build an object file
llcsv/csvcmds/csvjoincolumns.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvjoincolumns.cpp.o
.PHONY : llcsv/csvcmds/csvjoincolumns.cpp.o

llcsv/csvcmds/csvjoincolumns.i: llcsv/csvcmds/csvjoincolumns.cpp.i

.PHONY : llcsv/csvcmds/csvjoincolumns.i

# target to preprocess a source file
llcsv/csvcmds/csvjoincolumns.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvjoincolumns.cpp.i
.PHONY : llcsv/csvcmds/csvjoincolumns.cpp.i

llcsv/csvcmds/csvjoincolumns.s: llcsv/csvcmds/csvjoincolumns.cpp.s

.PHONY : llcsv/csvcmds/csvjoincolumns.s

# target to generate assembly for a file
llcsv/csvcmds/csvjoincolumns.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvjoincolumns.cpp.s
.PHONY : llcsv/csvcmds/csvjoincolumns.cpp.s

llcsv/csvcmds/csvmatchcolumns.o: llcsv/csvcmds/csvmatchcolumns.cpp.o

.PHONY : llcsv/csvcmds/csvmatchcolumns.o

# target to build an object file
llcsv/csvcmds/csvmatchcolumns.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvmatchcolumns.cpp.o
.PHONY : llcsv/csvcmds/csvmatchcolumns.cpp.o

llcsv/csvcmds/csvmatchcolumns.i: llcsv/csvcmds/csvmatchcolumns.cpp.i

.PHONY : llcsv/csvcmds/csvmatchcolumns.i

# target to preprocess a source file
llcsv/csvcmds/csvmatchcolumns.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvmatchcolumns.cpp.i
.PHONY : llcsv/csvcmds/csvmatchcolumns.cpp.i

llcsv/csvcmds/csvmatchcolumns.s: llcsv/csvcmds/csvmatchcolumns.cpp.s

.PHONY : llcsv/csvcmds/csvmatchcolumns.s

# target to generate assembly for a file
llcsv/csvcmds/csvmatchcolumns.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvmatchcolumns.cpp.s
.PHONY : llcsv/csvcmds/csvmatchcolumns.cpp.s

llcsv/csvcmds/csvoutputfile.o: llcsv/csvcmds/csvoutputfile.cpp.o

.PHONY : llcsv/csvcmds/csvoutputfile.o

# target to build an object file
llcsv/csvcmds/csvoutputfile.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvoutputfile.cpp.o
.PHONY : llcsv/csvcmds/csvoutputfile.cpp.o

llcsv/csvcmds/csvoutputfile.i: llcsv/csvcmds/csvoutputfile.cpp.i

.PHONY : llcsv/csvcmds/csvoutputfile.i

# target to preprocess a source file
llcsv/csvcmds/csvoutputfile.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvoutputfile.cpp.i
.PHONY : llcsv/csvcmds/csvoutputfile.cpp.i

llcsv/csvcmds/csvoutputfile.s: llcsv/csvcmds/csvoutputfile.cpp.s

.PHONY : llcsv/csvcmds/csvoutputfile.s

# target to generate assembly for a file
llcsv/csvcmds/csvoutputfile.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvoutputfile.cpp.s
.PHONY : llcsv/csvcmds/csvoutputfile.cpp.s

llcsv/csvcmds/csvreplacecolumns.o: llcsv/csvcmds/csvreplacecolumns.cpp.o

.PHONY : llcsv/csvcmds/csvreplacecolumns.o

# target to build an object file
llcsv/csvcmds/csvreplacecolumns.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvreplacecolumns.cpp.o
.PHONY : llcsv/csvcmds/csvreplacecolumns.cpp.o

llcsv/csvcmds/csvreplacecolumns.i: llcsv/csvcmds/csvreplacecolumns.cpp.i

.PHONY : llcsv/csvcmds/csvreplacecolumns.i

# target to preprocess a source file
llcsv/csvcmds/csvreplacecolumns.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvreplacecolumns.cpp.i
.PHONY : llcsv/csvcmds/csvreplacecolumns.cpp.i

llcsv/csvcmds/csvreplacecolumns.s: llcsv/csvcmds/csvreplacecolumns.cpp.s

.PHONY : llcsv/csvcmds/csvreplacecolumns.s

# target to generate assembly for a file
llcsv/csvcmds/csvreplacecolumns.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvreplacecolumns.cpp.s
.PHONY : llcsv/csvcmds/csvreplacecolumns.cpp.s

llcsv/csvcmds/csvselectcolumns.o: llcsv/csvcmds/csvselectcolumns.cpp.o

.PHONY : llcsv/csvcmds/csvselectcolumns.o

# target to build an object file
llcsv/csvcmds/csvselectcolumns.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvselectcolumns.cpp.o
.PHONY : llcsv/csvcmds/csvselectcolumns.cpp.o

llcsv/csvcmds/csvselectcolumns.i: llcsv/csvcmds/csvselectcolumns.cpp.i

.PHONY : llcsv/csvcmds/csvselectcolumns.i

# target to preprocess a source file
llcsv/csvcmds/csvselectcolumns.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvselectcolumns.cpp.i
.PHONY : llcsv/csvcmds/csvselectcolumns.cpp.i

llcsv/csvcmds/csvselectcolumns.s: llcsv/csvcmds/csvselectcolumns.cpp.s

.PHONY : llcsv/csvcmds/csvselectcolumns.s

# target to generate assembly for a file
llcsv/csvcmds/csvselectcolumns.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvselectcolumns.cpp.s
.PHONY : llcsv/csvcmds/csvselectcolumns.cpp.s

llcsv/csvcmds/csvselectrows.o: llcsv/csvcmds/csvselectrows.cpp.o

.PHONY : llcsv/csvcmds/csvselectrows.o

# target to build an object file
llcsv/csvcmds/csvselectrows.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvselectrows.cpp.o
.PHONY : llcsv/csvcmds/csvselectrows.cpp.o

llcsv/csvcmds/csvselectrows.i: llcsv/csvcmds/csvselectrows.cpp.i

.PHONY : llcsv/csvcmds/csvselectrows.i

# target to preprocess a source file
llcsv/csvcmds/csvselectrows.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvselectrows.cpp.i
.PHONY : llcsv/csvcmds/csvselectrows.cpp.i

llcsv/csvcmds/csvselectrows.s: llcsv/csvcmds/csvselectrows.cpp.s

.PHONY : llcsv/csvcmds/csvselectrows.s

# target to generate assembly for a file
llcsv/csvcmds/csvselectrows.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvselectrows.cpp.s
.PHONY : llcsv/csvcmds/csvselectrows.cpp.s

llcsv/csvcmds/csvsortrowsbycolumnkeys.o: llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.o

.PHONY : llcsv/csvcmds/csvsortrowsbycolumnkeys.o

# target to build an object file
llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.o
.PHONY : llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.o

llcsv/csvcmds/csvsortrowsbycolumnkeys.i: llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.i

.PHONY : llcsv/csvcmds/csvsortrowsbycolumnkeys.i

# target to preprocess a source file
llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.i
.PHONY : llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.i

llcsv/csvcmds/csvsortrowsbycolumnkeys.s: llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.s

.PHONY : llcsv/csvcmds/csvsortrowsbycolumnkeys.s

# target to generate assembly for a file
llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.s
.PHONY : llcsv/csvcmds/csvsortrowsbycolumnkeys.cpp.s

llcsv/llcsv.o: llcsv/llcsv.cpp.o

.PHONY : llcsv/llcsv.o

# target to build an object file
llcsv/llcsv.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/llcsv.cpp.o
.PHONY : llcsv/llcsv.cpp.o

llcsv/llcsv.i: llcsv/llcsv.cpp.i

.PHONY : llcsv/llcsv.i

# target to preprocess a source file
llcsv/llcsv.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/llcsv.cpp.i
.PHONY : llcsv/llcsv.cpp.i

llcsv/llcsv.s: llcsv/llcsv.cpp.s

.PHONY : llcsv/llcsv.s

# target to generate assembly for a file
llcsv/llcsv.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/llcsv.cpp.s
.PHONY : llcsv/llcsv.cpp.s

llcsv/util/directory.o: llcsv/util/directory.cpp.o

.PHONY : llcsv/util/directory.o

# target to build an object file
llcsv/util/directory.cpp.o:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/util/directory.cpp.o
.PHONY : llcsv/util/directory.cpp.o

llcsv/util/directory.i: llcsv/util/directory.cpp.i

.PHONY : llcsv/util/directory.i

# target to preprocess a source file
llcsv/util/directory.cpp.i:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/util/directory.cpp.i
.PHONY : llcsv/util/directory.cpp.i

llcsv/util/directory.s: llcsv/util/directory.cpp.s

.PHONY : llcsv/util/directory.s

# target to generate assembly for a file
llcsv/util/directory.cpp.s:
	$(MAKE) -f CMakeFiles/llcsv.dir/build.make CMakeFiles/llcsv.dir/llcsv/util/directory.cpp.s
.PHONY : llcsv/util/directory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... llcsv"
	@echo "... llcsv/csvcmds/csvappendcolumns.o"
	@echo "... llcsv/csvcmds/csvappendcolumns.i"
	@echo "... llcsv/csvcmds/csvappendcolumns.s"
	@echo "... llcsv/csvcmds/csvappendrows.o"
	@echo "... llcsv/csvcmds/csvappendrows.i"
	@echo "... llcsv/csvcmds/csvappendrows.s"
	@echo "... llcsv/csvcmds/csvcmds.o"
	@echo "... llcsv/csvcmds/csvcmds.i"
	@echo "... llcsv/csvcmds/csvcmds.s"
	@echo "... llcsv/csvcmds/csvinputfiles.o"
	@echo "... llcsv/csvcmds/csvinputfiles.i"
	@echo "... llcsv/csvcmds/csvinputfiles.s"
	@echo "... llcsv/csvcmds/csvjoincolumns.o"
	@echo "... llcsv/csvcmds/csvjoincolumns.i"
	@echo "... llcsv/csvcmds/csvjoincolumns.s"
	@echo "... llcsv/csvcmds/csvmatchcolumns.o"
	@echo "... llcsv/csvcmds/csvmatchcolumns.i"
	@echo "... llcsv/csvcmds/csvmatchcolumns.s"
	@echo "... llcsv/csvcmds/csvoutputfile.o"
	@echo "... llcsv/csvcmds/csvoutputfile.i"
	@echo "... llcsv/csvcmds/csvoutputfile.s"
	@echo "... llcsv/csvcmds/csvreplacecolumns.o"
	@echo "... llcsv/csvcmds/csvreplacecolumns.i"
	@echo "... llcsv/csvcmds/csvreplacecolumns.s"
	@echo "... llcsv/csvcmds/csvselectcolumns.o"
	@echo "... llcsv/csvcmds/csvselectcolumns.i"
	@echo "... llcsv/csvcmds/csvselectcolumns.s"
	@echo "... llcsv/csvcmds/csvselectrows.o"
	@echo "... llcsv/csvcmds/csvselectrows.i"
	@echo "... llcsv/csvcmds/csvselectrows.s"
	@echo "... llcsv/csvcmds/csvsortrowsbycolumnkeys.o"
	@echo "... llcsv/csvcmds/csvsortrowsbycolumnkeys.i"
	@echo "... llcsv/csvcmds/csvsortrowsbycolumnkeys.s"
	@echo "... llcsv/llcsv.o"
	@echo "... llcsv/llcsv.i"
	@echo "... llcsv/llcsv.s"
	@echo "... llcsv/util/directory.o"
	@echo "... llcsv/util/directory.i"
	@echo "... llcsv/util/directory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

